#!/bin/bash

echo "================================"
echo "Firestore Diagnostics"
echo "================================"
echo ""

# Check database exists
echo "📊 Checking databases..."
firebase firestore:databases:list

echo ""
echo "📋 Current Firestore configuration:"
cat firebase.json | grep -A 10 "firestore"

echo ""
echo "🔐 Checking deployed rules..."
firebase firestore:rules:list 2>/dev/null || echo "Could not list rules"

echo ""
echo "================================"
echo "Test Plan"
echo "================================"
echo ""
echo "Let's test if Firestore is working by creating a test document."
echo "This will help us identify the exact issue."
echo ""
echo "Run this in your browser console while logged in:"
echo ""
echo "// Test Firestore Write"
echo "import { doc, setDoc } from 'firebase/firestore';"
echo "import { db, auth } from './config/firebase';"
echo ""
echo "const testWrite = async () => {"
echo "  try {"
echo "    const uid = auth.currentUser?.uid;"
echo "    if (!uid) {"
echo "      console.error('❌ Not logged in');"
echo "      return;"
echo "    }"
echo "    "
echo "    console.log('✅ User ID:', uid);"
echo "    "
echo "    // Try to write a test document"
echo "    await setDoc(doc(db, \`users/\${uid}/test/test1\`), {"
echo "      timestamp: new Date().toISOString(),"
echo "      message: 'Hello from test'"
echo "    });"
echo "    "
echo "    console.log('✅ Write successful!');"
echo "  } catch (error) {"
echo "    console.error('❌ Write failed:', error);"
echo "    console.error('Error code:', error.code);"
echo "    console.error('Error message:', error.message);"
echo "  }"
echo "};"
echo ""
echo "testWrite();"
echo ""
echo "================================"
echo "Possible Issues:"
echo "================================"
echo ""
echo "1. ❌ Database in wrong location"
echo "   - Check Firebase Console → Settings"
echo "   - Verify database location matches your app region"
echo ""
echo "2. ❌ Rules not deployed correctly"
echo "   - Run: firebase deploy --only firestore:rules"
echo ""
echo "3. ❌ IndexedDB persistence conflict"
echo "   - Clear browser data"
echo "   - Try in incognito mode"
echo ""
echo "4. ❌ Multiple Firebase projects"
echo "   - Verify .env has correct project ID"
echo ""
echo "5. ❌ Browser extension interference"
echo "   - Disable ad blockers/extensions"
echo ""
